export interface BiomarkerReference {
  name: string;
  displayName: string;
  unit: string;
  category: 'liver' | 'kidney' | 'thyroid' | 'metabolic' | 'blood' | 'heart' | 'nutrients';
  labRangeLow: number;
  labRangeHigh: number;
  optimalRangeLow: number;
  optimalRangeHigh: number;
  genderSpecific: boolean;
  maleOptimalLow?: number;
  maleOptimalHigh?: number;
  femaleOptimalLow?: number;
  femaleOptimalHigh?: number;
  description: string;
}

export const biomarkerReferences: BiomarkerReference[] = [
  // Blood (8)
  {
    name: 'Hemoglobin',
    displayName: 'Hemoglobin (Hb)',
    unit: 'g/dL',
    category: 'blood',
    labRangeLow: 12.0,
    labRangeHigh: 17.5,
    optimalRangeLow: 13.5,
    optimalRangeHigh: 15.5,
    genderSpecific: true,
    maleOptimalLow: 14.0,
    maleOptimalHigh: 15.5,
    femaleOptimalLow: 13.5,
    femaleOptimalHigh: 15.0,
    description: 'Protein in red blood cells that carries oxygen throughout the body',
  },
  {
    name: 'RBC Count',
    displayName: 'Red Blood Cell Count',
    unit: 'million cells/μL',
    category: 'blood',
    labRangeLow: 4.2,
    labRangeHigh: 5.4,
    optimalRangeLow: 4.5,
    optimalRangeHigh: 5.2,
    genderSpecific: false,
    description: 'Number of red blood cells that carry oxygen',
  },
  {
    name: 'WBC Count',
    displayName: 'White Blood Cell Count',
    unit: 'cells/μL',
    category: 'blood',
    labRangeLow: 4500,
    labRangeHigh: 11000,
    optimalRangeLow: 5000,
    optimalRangeHigh: 8500,
    genderSpecific: false,
    description: 'Number of white blood cells that fight infections',
  },
  {
    name: 'Platelet Count',
    displayName: 'Platelet Count',
    unit: 'cells/μL',
    category: 'blood',
    labRangeLow: 150000,
    labRangeHigh: 400000,
    optimalRangeLow: 200000,
    optimalRangeHigh: 350000,
    genderSpecific: false,
    description: 'Cells that help with blood clotting',
  },
  {
    name: 'MCV',
    displayName: 'Mean Corpuscular Volume',
    unit: 'fL',
    category: 'blood',
    labRangeLow: 80,
    labRangeHigh: 100,
    optimalRangeLow: 82,
    optimalRangeHigh: 96,
    genderSpecific: false,
    description: 'Average size of red blood cells',
  },
  {
    name: 'MCH',
    displayName: 'Mean Corpuscular Hemoglobin',
    unit: 'pg',
    category: 'blood',
    labRangeLow: 27,
    labRangeHigh: 33,
    optimalRangeLow: 28,
    optimalRangeHigh: 32,
    genderSpecific: false,
    description: 'Average amount of hemoglobin per red blood cell',
  },
  {
    name: 'MCHC',
    displayName: 'Mean Corpuscular Hemoglobin Concentration',
    unit: 'g/dL',
    category: 'blood',
    labRangeLow: 32,
    labRangeHigh: 36,
    optimalRangeLow: 32.5,
    optimalRangeHigh: 35.5,
    genderSpecific: false,
    description: 'Average concentration of hemoglobin in red blood cells',
  },
  {
    name: 'ESR',
    displayName: 'Erythrocyte Sedimentation Rate',
    unit: 'mm/hr',
    category: 'blood',
    labRangeLow: 0,
    labRangeHigh: 20,
    optimalRangeLow: 0,
    optimalRangeHigh: 10,
    genderSpecific: false,
    description: 'Marker of inflammation in the body',
  },

  // Metabolic (7)
  {
    name: 'Fasting Glucose',
    displayName: 'Fasting Blood Glucose',
    unit: 'mg/dL',
    category: 'metabolic',
    labRangeLow: 70,
    labRangeHigh: 100,
    optimalRangeLow: 75,
    optimalRangeHigh: 90,
    genderSpecific: false,
    description: 'Blood sugar level after 8+ hours of fasting',
  },
  {
    name: 'HbA1c',
    displayName: 'Glycated Hemoglobin (HbA1c)',
    unit: '%',
    category: 'metabolic',
    labRangeLow: 4.0,
    labRangeHigh: 5.6,
    optimalRangeLow: 4.5,
    optimalRangeHigh: 5.2,
    genderSpecific: false,
    description: '2-3 month average of blood glucose levels',
  },
  {
    name: 'Fasting Insulin',
    displayName: 'Fasting Insulin',
    unit: 'mIU/L',
    category: 'metabolic',
    labRangeLow: 2.0,
    labRangeHigh: 20.0,
    optimalRangeLow: 2.0,
    optimalRangeHigh: 8.0,
    genderSpecific: false,
    description: 'Hormone that regulates blood sugar levels',
  },
  {
    name: 'HOMA-IR',
    displayName: 'HOMA Insulin Resistance Index',
    unit: 'ratio',
    category: 'metabolic',
    labRangeLow: 0.5,
    labRangeHigh: 5.0,
    optimalRangeLow: 0.5,
    optimalRangeHigh: 2.0,
    genderSpecific: false,
    description: 'Measure of insulin resistance calculated from glucose and insulin',
  },
  {
    name: 'Total Cholesterol',
    displayName: 'Total Cholesterol',
    unit: 'mg/dL',
    category: 'metabolic',
    labRangeLow: 0,
    labRangeHigh: 200,
    optimalRangeLow: 0,
    optimalRangeHigh: 180,
    genderSpecific: false,
    description: 'Total amount of cholesterol in the blood',
  },
  {
    name: 'Triglycerides',
    displayName: 'Triglycerides',
    unit: 'mg/dL',
    category: 'metabolic',
    labRangeLow: 0,
    labRangeHigh: 150,
    optimalRangeLow: 0,
    optimalRangeHigh: 100,
    genderSpecific: false,
    description: 'Type of fat in the blood',
  },
  {
    name: 'Uric Acid',
    displayName: 'Uric Acid',
    unit: 'mg/dL',
    category: 'metabolic',
    labRangeLow: 3.5,
    labRangeHigh: 7.2,
    optimalRangeLow: 3.5,
    optimalRangeHigh: 6.0,
    genderSpecific: false,
    description: 'Waste product from purine metabolism',
  },

  // Liver (7)
  {
    name: 'ALT (SGPT)',
    displayName: 'Alanine Aminotransferase (ALT/SGPT)',
    unit: 'U/L',
    category: 'liver',
    labRangeLow: 7,
    labRangeHigh: 55,
    optimalRangeLow: 7,
    optimalRangeHigh: 35,
    genderSpecific: false,
    description: 'Enzyme found mainly in liver cells',
  },
  {
    name: 'AST (SGOT)',
    displayName: 'Aspartate Aminotransferase (AST/SGOT)',
    unit: 'U/L',
    category: 'liver',
    labRangeLow: 10,
    labRangeHigh: 40,
    optimalRangeLow: 10,
    optimalRangeHigh: 32,
    genderSpecific: false,
    description: 'Enzyme found in liver, heart and muscles',
  },
  {
    name: 'ALP',
    displayName: 'Alkaline Phosphatase (ALP)',
    unit: 'U/L',
    category: 'liver',
    labRangeLow: 30,
    labRangeHigh: 120,
    optimalRangeLow: 40,
    optimalRangeHigh: 100,
    genderSpecific: false,
    description: 'Enzyme involved in bone and liver function',
  },
  {
    name: 'GGT',
    displayName: 'Gamma-Glutamyl Transferase (GGT)',
    unit: 'U/L',
    category: 'liver',
    labRangeLow: 0,
    labRangeHigh: 55,
    optimalRangeLow: 0,
    optimalRangeHigh: 40,
    genderSpecific: false,
    description: 'Enzyme associated with liver and bile duct function',
  },
  {
    name: 'Total Bilirubin',
    displayName: 'Total Bilirubin',
    unit: 'mg/dL',
    category: 'liver',
    labRangeLow: 0.1,
    labRangeHigh: 1.2,
    optimalRangeLow: 0.1,
    optimalRangeHigh: 1.0,
    genderSpecific: false,
    description: 'Pigment produced from breakdown of hemoglobin',
  },
  {
    name: 'Direct Bilirubin',
    displayName: 'Direct Bilirubin (Conjugated)',
    unit: 'mg/dL',
    category: 'liver',
    labRangeLow: 0.0,
    labRangeHigh: 0.3,
    optimalRangeLow: 0.0,
    optimalRangeHigh: 0.2,
    genderSpecific: false,
    description: 'Bilirubin after processing by the liver',
  },
  {
    name: 'Albumin',
    displayName: 'Serum Albumin',
    unit: 'g/dL',
    category: 'liver',
    labRangeLow: 3.5,
    labRangeHigh: 5.5,
    optimalRangeLow: 4.0,
    optimalRangeHigh: 5.3,
    genderSpecific: false,
    description: 'Major protein produced by the liver',
  },

  // Kidney (5)
  {
    name: 'Creatinine',
    displayName: 'Serum Creatinine',
    unit: 'mg/dL',
    category: 'kidney',
    labRangeLow: 0.6,
    labRangeHigh: 1.2,
    optimalRangeLow: 0.7,
    optimalRangeHigh: 1.0,
    genderSpecific: true,
    maleOptimalLow: 0.8,
    maleOptimalHigh: 1.0,
    femaleOptimalLow: 0.7,
    femaleOptimalHigh: 0.9,
    description: 'Waste product of muscle metabolism filtered by kidneys',
  },
  {
    name: 'BUN',
    displayName: 'Blood Urea Nitrogen (BUN)',
    unit: 'mg/dL',
    category: 'kidney',
    labRangeLow: 7,
    labRangeHigh: 20,
    optimalRangeLow: 7,
    optimalRangeHigh: 18,
    genderSpecific: false,
    description: 'Waste product from protein breakdown',
  },
  {
    name: 'eGFR',
    displayName: 'Estimated Glomerular Filtration Rate',
    unit: 'mL/min/1.73m²',
    category: 'kidney',
    labRangeLow: 60,
    labRangeHigh: 999,
    optimalRangeLow: 90,
    optimalRangeHigh: 999,
    genderSpecific: false,
    description: 'Estimated kidney filtration function',
  },
  {
    name: 'Uric Acid (Kidney)',
    displayName: 'Uric Acid',
    unit: 'mg/dL',
    category: 'kidney',
    labRangeLow: 3.5,
    labRangeHigh: 7.2,
    optimalRangeLow: 3.5,
    optimalRangeHigh: 6.0,
    genderSpecific: false,
    description: 'Waste product filtered by kidneys',
  },
  {
    name: 'Microalbumin',
    displayName: 'Microalbumin (Urine)',
    unit: 'mg/24hr',
    category: 'kidney',
    labRangeLow: 0,
    labRangeHigh: 30,
    optimalRangeLow: 0,
    optimalRangeHigh: 20,
    genderSpecific: false,
    description: 'Small amount of protein in urine indicating early kidney damage',
  },

  // Thyroid (5)
  {
    name: 'TSH',
    displayName: 'Thyroid Stimulating Hormone (TSH)',
    unit: 'mIU/L',
    category: 'thyroid',
    labRangeLow: 0.4,
    labRangeHigh: 4.0,
    optimalRangeLow: 1.0,
    optimalRangeHigh: 2.5,
    genderSpecific: false,
    description: 'Hormone that regulates thyroid function',
  },
  {
    name: 'Free T3',
    displayName: 'Free Triiodothyronine (Free T3)',
    unit: 'pg/mL',
    category: 'thyroid',
    labRangeLow: 2.3,
    labRangeHigh: 4.2,
    optimalRangeLow: 2.8,
    optimalRangeHigh: 3.8,
    genderSpecific: false,
    description: 'Active thyroid hormone T3',
  },
  {
    name: 'Free T4',
    displayName: 'Free Thyroxine (Free T4)',
    unit: 'ng/dL',
    category: 'thyroid',
    labRangeLow: 0.8,
    labRangeHigh: 1.8,
    optimalRangeLow: 1.0,
    optimalRangeHigh: 1.5,
    genderSpecific: false,
    description: 'Thyroid hormone T4 that circulates freely',
  },
  {
    name: 'Anti-TPO',
    displayName: 'Anti-Thyroid Peroxidase Antibody',
    unit: 'IU/mL',
    category: 'thyroid',
    labRangeLow: 0,
    labRangeHigh: 35,
    optimalRangeLow: 0,
    optimalRangeHigh: 10,
    genderSpecific: false,
    description: 'Antibody against thyroid enzyme (marker of autoimmune thyroid)',
  },
  {
    name: 'Anti-Thyroglobulin',
    displayName: 'Anti-Thyroglobulin Antibody',
    unit: 'IU/mL',
    category: 'thyroid',
    labRangeLow: 0,
    labRangeHigh: 40,
    optimalRangeLow: 0,
    optimalRangeHigh: 15,
    genderSpecific: false,
    description: 'Antibody against thyroid protein (marker of autoimmune thyroid)',
  },

  // Heart (5)
  {
    name: 'LDL Cholesterol',
    displayName: 'Low-Density Lipoprotein (LDL)',
    unit: 'mg/dL',
    category: 'heart',
    labRangeLow: 0,
    labRangeHigh: 100,
    optimalRangeLow: 0,
    optimalRangeHigh: 70,
    genderSpecific: false,
    description: '"Bad" cholesterol that can clog arteries',
  },
  {
    name: 'HDL Cholesterol',
    displayName: 'High-Density Lipoprotein (HDL)',
    unit: 'mg/dL',
    category: 'heart',
    labRangeLow: 40,
    labRangeHigh: 200,
    optimalRangeLow: 50,
    optimalRangeHigh: 200,
    genderSpecific: true,
    maleOptimalLow: 50,
    maleOptimalHigh: 200,
    femaleOptimalLow: 60,
    femaleOptimalHigh: 200,
    description: '"Good" cholesterol that protects heart health',
  },
  {
    name: 'Triglycerides (Heart)',
    displayName: 'Triglycerides',
    unit: 'mg/dL',
    category: 'heart',
    labRangeLow: 0,
    labRangeHigh: 150,
    optimalRangeLow: 0,
    optimalRangeHigh: 100,
    genderSpecific: false,
    description: 'Type of fat in blood related to heart disease risk',
  },
  {
    name: 'hs-CRP',
    displayName: 'High-Sensitivity C-Reactive Protein',
    unit: 'mg/L',
    category: 'heart',
    labRangeLow: 0.0,
    labRangeHigh: 3.0,
    optimalRangeLow: 0.0,
    optimalRangeHigh: 1.0,
    genderSpecific: false,
    description: 'Marker of inflammation related to heart disease risk',
  },
  {
    name: 'Homocysteine',
    displayName: 'Homocysteine',
    unit: 'μmol/L',
    category: 'heart',
    labRangeLow: 5,
    labRangeHigh: 15,
    optimalRangeLow: 5,
    optimalRangeHigh: 10,
    genderSpecific: false,
    description: 'Amino acid that affects heart health when elevated',
  },

  // Nutrients (8)
  {
    name: 'Vitamin D (25-OH)',
    displayName: 'Vitamin D (25-Hydroxy)',
    unit: 'ng/mL',
    category: 'nutrients',
    labRangeLow: 30,
    labRangeHigh: 100,
    optimalRangeLow: 50,
    optimalRangeHigh: 80,
    genderSpecific: false,
    description: 'Fat-soluble vitamin essential for bone health and immunity',
  },
  {
    name: 'Vitamin B12',
    displayName: 'Vitamin B12 (Cobalamin)',
    unit: 'pg/mL',
    category: 'nutrients',
    labRangeLow: 200,
    labRangeHigh: 900,
    optimalRangeLow: 400,
    optimalRangeHigh: 800,
    genderSpecific: false,
    description: 'Essential for red blood cells and nerve function',
  },
  {
    name: 'Folate',
    displayName: 'Serum Folate',
    unit: 'ng/mL',
    category: 'nutrients',
    labRangeLow: 5.4,
    labRangeHigh: 16,
    optimalRangeLow: 7,
    optimalRangeHigh: 14,
    genderSpecific: false,
    description: 'B-vitamin essential for DNA synthesis and cell division',
  },
  {
    name: 'Iron',
    displayName: 'Serum Iron',
    unit: 'μg/dL',
    category: 'nutrients',
    labRangeLow: 60,
    labRangeHigh: 170,
    optimalRangeLow: 80,
    optimalRangeHigh: 150,
    genderSpecific: false,
    description: 'Mineral essential for oxygen transport in blood',
  },
  {
    name: 'Ferritin',
    displayName: 'Serum Ferritin',
    unit: 'ng/mL',
    category: 'nutrients',
    labRangeLow: 30,
    labRangeHigh: 400,
    optimalRangeLow: 40,
    optimalRangeHigh: 200,
    genderSpecific: true,
    maleOptimalLow: 60,
    maleOptimalHigh: 170,
    femaleOptimalLow: 40,
    femaleOptimalHigh: 120,
    description: 'Protein that stores iron in the body',
  },
  {
    name: 'TIBC',
    displayName: 'Total Iron-Binding Capacity',
    unit: 'μg/dL',
    category: 'nutrients',
    labRangeLow: 250,
    labRangeHigh: 425,
    optimalRangeLow: 250,
    optimalRangeHigh: 400,
    genderSpecific: false,
    description: 'Capacity of blood to transport iron',
  },
  {
    name: 'Calcium',
    displayName: 'Serum Calcium',
    unit: 'mg/dL',
    category: 'nutrients',
    labRangeLow: 8.5,
    labRangeHigh: 10.5,
    optimalRangeLow: 8.8,
    optimalRangeHigh: 10.2,
    genderSpecific: false,
    description: 'Mineral essential for bones, muscles and nerve function',
  },
  {
    name: 'Magnesium',
    displayName: 'Serum Magnesium',
    unit: 'mg/dL',
    category: 'nutrients',
    labRangeLow: 1.7,
    labRangeHigh: 2.2,
    optimalRangeLow: 1.8,
    optimalRangeHigh: 2.1,
    genderSpecific: false,
    description: 'Mineral involved in over 300 enzymatic reactions',
  },
];
